name: EB Deployment for Infra add App

on:
  push:
    branches: ["main"]

jobs:
  EB-Deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Setup Tofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.7.2
        tofu_wrapper: false

    - name: Tofu Init
      run: tofu Init --recursive

    - name: Tofu fmt
      run: tofu fmt --recursive

    - name: Tofu Validate
      run: tofu validate

    - name: Todu Plan
      run: tofu plan

    - name: Tofu Apply
      run: tofu apply -auto-approve

    - name: Export tofu outputs
      id: tfout
      run: |
        echo "EB_APP=$(tofu output -raw app_name)" >> $GITHUB_OUTPUT
        echo "EB_ENV=$(tofu output -raw env_name)" >> $GITHUB_OUTPUT

    - name: Generate deployment package
      working-directory: ./sample
      run: zip -r ../deploy.zip .

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ steps.tfout.outputs.EB_APP }}
        environment_name: ${{ steps.tfout.outputs.EB_ENV }}
        version_label: ${{ github.sha }}
        region: ${{ vars.AWS_DEFAULT_REGION }}
        deployment_package: deploy.zip


